name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
          # Note: $SSH_PRIVATE_KEY_WITH_PASSWORD é a variável secreta que contém a chave SSH privada protegida por senha.

      - name: SSH into DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Comandos de implantação aqui

      - name: Cleanup SSH agent
        run: ssh-agent -k
